name: gnut_identifier
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
 
  flutx: ^0.1.2
  connectivity_plus: ^3.0.2
  dio: ^5.1.2

  cupertino_icons: ^1.0.3
  cached_network_image: ^3.2.0
  flutter_form_builder: ^8.0.0
  form_builder_validators: ^8.3.0
  url_launcher: ^6.1.9
  geolocator: ^9.0.2
  image_picker: ^0.8.6+1
  shimmer: ^2.0.0
  intl: ^0.17.0
  hive: ^2.0.6
  hive_flutter: ^1.1.0
  feather_icons: ^1.2.0
  flutter_easyloading: ^3.0.5
  fluttertoast: ^8.0.9

#Dependency for ai model
  flutter_vision: ^1.1.4

  get: ^4.6.5
  sqflite: ^2.2.4+1
  shared_preferences: ^2.0.17
  flutter_html: ^3.0.0-beta.2
  table_calendar: ^3.0.9
  material_design_icons_flutter: ^7.0.7296

dependency_overrides:
  intl: any
  google_fonts: any
  flutter_svg: any

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^2.0.0
  build_runner: ^2.3.2
  change_app_package_name: ^1.0.0

  # Icons
  flutter_feather_icons: ^2.0.0+1
  flutter_lints: ^2.0.1

  # flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/aimodel/
    - assets/aimodel/variety_identifier_model.tflite
    - assets/aimodel/labels_variety.txt
    - assets/images/logo.png
    - assets/images/ai_prediction_1.jpeg
    - assets/images/ai_prediction.jpeg
    - assets/images/tomorrow/